####################################################################
###              AutoRemediation of Ntechnology                  ###
####################################################################
##  REALIZA LA INSTALACION DE UN PAQUETE EN LINUX

- hosts: localhost

  vars:

  tasks:

# CAMBIA EL ESTADO DEL TICKETID A EN CURSO
  - name: Cambia el estado del Ticket a En Curso
    command: ls -lrt
    register: comando
  - debug: var=comando
